engines:
  eslint:
    enabled: true
ratings:
  paths:
    - angular/**
    - "**.js"
languages:
  Ruby: false
  JavaScript: true
  PHP: true
  Python: false
exclude_paths:
- "gulpfile.js"
- "public/js/vendor.js"
- "public/dist/js/app.js"
- "tasks/**"
- "tests/**"
